turnk/src/ByDay.Web.UI/Controllers/ProductController.cs
using ByDay.Business.Products;
using ByDay.Model;
using ByDay.Web.UI.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ByDay.Web.UI.Controllers
{

    [Authorize]
    public class ProductController : Controller
    {
        ProductModel product = new ProductModel();
        ProductService productService = new ProductService();
        public ActionResult Index()
        {
     
            product.BreadCrumbLinks.Add(new BreadCrumb
            {
                Text = string.Format("Home"),
                // Seperator = " > ",
                Url = string.Format("/Recipe/Index")
            });
            product.BreadCrumbLinks.Add(new BreadCrumb { Text = "View product", Url = "" });
            ViewBag.BreadCrumbs = product.BreadCrumbLinks;
            var res = productService.GetAll().ToList();
            ViewBag.productList = AutoMapper.Mapper.Map<List<ProductModel>>(res);
            return View();
        }
        [HttpGet]
        public ActionResult AddProduct()
        {
             var categoryList   = AutoMapper.Mapper.Map<List<ViewModel.VMProductCategory>>(productService.GetCategories().ToList());
            product.ProductCategoryList = categoryList;

            product.BreadCrumbLinks.Add(new BreadCrumb
            {
                Text = string.Format("Home"),
                // Seperator = " > ",
                Url = string.Format("/Recipe/Index")
            });
            product.BreadCrumbLinks.Add(new BreadCrumb { Text = "Add product", Url = "" });
            ViewBag.BreadCrumbs = product.BreadCrumbLinks;
            return View(product);

        }
        [HttpPost]
        public ActionResult AddProduct(ProductModel product)
        {
             product.URL = UploadProductImage(product);
            if (Request.Files.Count > 1)
            {
                product.ProductImages = new List<ProductImage>();
                for (int i = 1; i < Request.Files.Count; i++)
                {
                    if (!string.IsNullOrEmpty(Request.Files[i].FileName))
                        product.ProductImages.Add(UploadOtherProductImages(Request.Files[i]));
                }
            }
            var productCommand = AutoMapper.Mapper.Map<ProductCommand>(product);
            productService.Insert(productCommand);
                return RedirectToAction("Index");
        }
     

        [HttpPost]
        public ActionResult AddProductCategory(string categoryName)
        {
            var res = productService.InsertProductCategory(categoryName);
            return Json(res, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public ActionResult GetProduct(int page)
        {
            int pageSize = 15;
            int skipRecord = pageSize * (page- 1);
            var productList = AutoMapper.Mapper.Map<List<ProductModel>>(productService.GetAll());
            productList = productList.OrderBy(x => x.Name).Skip(skipRecord).Take(pageSize).ToList();
            return Json(productList, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public ActionResult GetFilterProduct(string searchLike)
       {
          //  var recipies = _recipeService.SearchRecipiesResult(searchLike).ToList();
            var productList = AutoMapper.Mapper.Map<List<ProductModel>>(productService.GetSelectProduct(searchLike));
            return Json(productList, JsonRequestBehavior.AllowGet);
        }




        [HttpPost]
        public ActionResult GetAllProduct()
        {
            var productList = AutoMapper.Mapper.Map<List<ProductModel>>(productService.GetAll());
            return Json(productList, JsonRequestBehavior.AllowGet);

        }



        [HttpPost]
        public ActionResult AddProductSubCategory(string subCategoryName, int categoryId)
        {
            var UpdatedProductSubCategory = productService.InsertProductSubCategory(subCategoryName,categoryId);
            var res = AutoMapper.Mapper.Map<ViewModel.VMProductSubCategory>(UpdatedProductSubCategory);
            return Json(res, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public JsonResult GetProductSubCategory(int categoryId )
        {
            var data = productService.GetSubCategories(categoryId).Select(x => new ProductModel() { Name = x.Name, Id = x.Id }).ToList();
            return Json(data, JsonRequestBehavior.AllowGet);

        }
        [HttpGet]
        public ActionResult EditProduct(int id)
        {


            var products = productService.GetProductById(id).ToList();
            var productList = AutoMapper.Mapper.Map<ProductModel>(products[0]);
            productList.ProductName = products[0].Name;
            var subCategory = AutoMapper.Mapper.Map<ViewModel.VMProductSubCategory>(productService.GetSubCategoriesById(productList.SubCategoryId).FirstOrDefault());
            var Category = AutoMapper.Mapper.Map<ViewModel.VMProductCategory>(productService.GetCategoriesById(subCategory.CategoryId).FirstOrDefault());

            ViewBag.CategoryName = Category.Name;
            ViewBag.CategorySubName = subCategory.Name;
            ViewBag.CategoryId = Category.Id;
            ViewBag.CategorySubId = subCategory.Id;
            product.BreadCrumbLinks.Add(new BreadCrumb
            {
                Text = string.Format("Home"),
                // Seperator = " > ",
                Url = string.Format("/Recipe/Index")
            });
            product.BreadCrumbLinks.Add(new BreadCrumb { Text = "Edit product", Url = "" });
            ViewBag.BreadCrumbs = product.BreadCrumbLinks;
            var categoryList = AutoMapper.Mapper.Map<List<ViewModel.VMProductCategory>>(productService.GetCategories().ToList());
            productList.ProductCategoryList = categoryList;
            return View(productList);
        }
        [HttpPost]
        public ActionResult EditProduct(ProductModel product)
        {
            if (product.FileName != null)
            {
                product.URL = UploadProductImage(product);
            }
            if (Request.Files.Count > 1)
            {
                //product.ProductImages = new List<ProductImage>();
                for (int i = 1; i < Request.Files.Count; i++)
                {
                    if (!string.IsNullOrEmpty(Request.Files[i].FileName))
                        product.ProductImages.Add(UploadOtherProductImages(Request.Files[i]));
                }
            }
            var productCommand = AutoMapper.Mapper.Map<ProductCommand>(product);
            productService.Update(productCommand);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult DeleteProduct(int productId)
        {
            var proRes = productService.Delete(productId);
            return Json(1, JsonRequestBehavior.AllowGet);
        }


        public string UploadProductImage(ProductModel product)
        {
            var file = product.FileName;
            String timeStamp = Guid.NewGuid().ToString();
            var path = Path.Combine("/ProductImages/", string.Format("{0}_{1}", timeStamp, product.FileName.FileName));
            System.Web.HttpContext.Current.Server.MapPath(path);
            file.SaveAs(Server.MapPath(path));
            return path;
        }

        public ProductImage UploadOtherProductImages(HttpPostedFileBase filename)
        {
            ProductImage image = new ProductImage();
            var file = filename;
            String timeStamp = Guid.NewGuid().ToString();
            var path = Path.Combine("/ProductImages/", string.Format("{0}_{1}", timeStamp, filename.FileName));
            System.Web.HttpContext.Current.Server.MapPath(path);
            file.SaveAs(Server.MapPath(path));
            image.URL = path;
            return image;
        }
    }
}

turnk/src/ByDay.Web.UI/Views/Product/AddProduct.cshtml
@model ByDay.Web.UI.Models.ProductModel
@{
    ViewBag.Title = "AddProduct";
}
@using (Html.BeginForm("AddProduct", "Product", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data", @id = "productForm" }))
{

<div class="row">
    <div class="col-md-6">
        <div class="form-main-container">
            <div class="form-heading">
                <span class="form-heading-icon"><i class="fa fa-bars"></i></span>
                <h4>Product Category & Sub-category</h4>
            </div>
            <div class="form-container">
                <div class="form-horizontal">
                    <div class="form-group category-form" id="categoryLabel-form">
                        <label class="col-md-4 control-label required-filed">Category Name</label>
                        <div class="col-md-8">
                            @Html.DropDownListFor(m => m.Id, new SelectList(Model.ProductCategoryList, "Id", "Name", Model.Id), "--Select--", new { @class = "form-control", id = "selectName" })
                            <a title="Add new category" id="category-form-btn" >+</a>
                        </div>
                    </div>
                    <div class="form-group sub-form-gp" id="category-form">
                          <div class="col-md-12">
                           <div class="r1">
                                @Html.TextBoxFor(m => m.CategoryName, new
                           {
                               @class = "form-control",
                               @id = "pro-validid",
                               @placeholder = "New Category Name",
                               maxlength = "100"
                           })
                                <p id="proName-error" class="field-validation-error"></p>
                            </div>
                            <div class="r2">
                                <input type="button" value="Save" onclick = "return submitProductCategoryData();" class="theme-btn">
                            </div>
                      </div>
                    </div>
                    <div class="form-group category-form">
                        <label class="col-md-4 control-label required-filed">Sub-category Name</label>
                        <div class="col-md-8" id="subcatId">
                            @Html.DropDownListFor(m => m.SubCategoryId, new SelectList(Model.ProductSubCategoryList, "Id", "Name", Model.Id), "--Select--", new { @class = "form-control", id = "pro-subCatgory" })
                           <a title="Add new category" id="subcategory-form-btn">+</a>
                        </div>
                    </div>
                    <div class="form-group subcategory-form-gp"  id="subcategory-form">
                        <div class="col-md-12">
                            <div class="r1">
                            <input type="text" readonly name="categoryId" class="form-control" id="catId" placeholder=""></div>
                            <div class="r2">
                                @Html.TextBoxFor(m => m.Name, new
                           {
                               @class = "form-control",
                               @id = "proSub-validid",
                               @placeholder = "New Sub Category",
                               maxlength = "100"
                           })
                                <p id="proSubName-error" class="field-validation-error"></p>
                            </div>
                            <div class="r3">
                                <input type="button" value="Save" onclick = "return submitProductSubCategoryData()" class="theme-btn">
                            </div>
                        </div>
                        </div>
                     </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-main-container">
            <div class="form-heading">
                <span class="form-heading-icon"><i class="fa fa-bars"></i></span>
                <h4>Product</h4>
            </div>
            <div class="form-container">
                <div class="form-horizontal">
                      <div class="form-group">
                        <label class="col-md-4 control-label required-filed">Product Name</label>
                        <div class="col-md-8">
                           @Html.TextBoxFor(x => x.ProductName, new
                       {
                           @class = "form-control",
                           @id = "proname-validid",
                           @placeholder = "Product Name",
                           maxlength = "100"
                       })
                            <p id="productName-error" class="field-validation-error" ></p>

                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 control-label required-filed">Product Price</label>
                        <div class="col-md-8">
                        @Html.TextBoxFor(m => m.Price, new
                   {
                       @class = "form-control",
                       @id = "price-validid",
                       @placeholder = "Price",
                       oncopy = "return false",
                       onpaste = "return false",
                       oncut = "return false",
                   

                       maxlength = "7"
                   })


                            <p id="price-error" class="field-validation-error" ></p>

                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 control-label required-filed">Product Type</label>
                        <div class="col-md-8">
                            @Html.DropDownListFor(m => m.Type, new SelectList(new[]{
                                 new { Value = "", Text = "--Select--" },
                                 new { Value = "G", Text = "Gift" },
                                 new { Value = "C", Text = "Card" }
                             }, "Value", "Text"), new { @class = "form-control", @id = "producttype-validid" })

                            <p id="producttype-error" class="field-validation-error" ></p>
                      
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 control-label">Needs custom photo</label>
                        <div class="col-md-8">
                            @Html.DropDownListFor(m => m.IsCustomizable, new SelectList(new[]{
                                   new { Value = "false", Text = "No" },
                                 new { Value = "true", Text = "Yes" }
                             }, "Value", "Text"), new { @class = "form-control", @id = "iscustom-validid" })
                            <p id="iscustom-error" class="field-validation-error"></p>

                        </div>
                    </div>
                    <div class="form-group upload-product-image">
                        <label class="col-md-4 control-label required-filed">Upload Image</label>
                        <div class="col-md-8 upload-product-image">
                            <div class="col-md-4">


                                <img class="upload-image" src="/Content/images/byDefault.png">
                            </div>

                            <div class="col-md-8">
                                <label for="file-upload" class="custom-file-upload" id="custom-file-upload">
                                    <i class="fa fa-image"></i> Image Upload
                                </label>
                                <input type="file" id="file-upload" class="form-control uploadimg" name="FileName" onchange="SelectProductImage(this);">

                                <p id="uploadimage-error" class="field-validation-error"></p>

                            </div>

                        </div>
                        </div>
                    <div id="extraImages_" class="multi-image-wrap"></div>
                    <div class="form-group" id="more-option">
                        <label class="col-md-4 control-label">&nbsp;</label>
                        <div class="col-md-8">
                            <div class="form-actions">
                                <button type="button" id="btnAddMore" onclick="AddMoreRowsImage()" class="btn btn-default"> + Add More Image</button>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-2">
                            @*<input type="submit" value="Save" class="theme-btn">*@
                            <input type="button" value="save" id="savePrductBtn" class="theme-btn">
                        </div>
                        <div class="col-md-4"><input type="button" value="Reset" id="reset-product-btn" class="btn-default"></div>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>

</div>
}
@section scripts{

    <script>
    $('#reset-product-btn').click(function () {
    
        $('#productForm')[0].reset();
        $("#pro-subCatgory").html("<option value=''>--Select--</option>");
        $('#pro-subCatgory').attr("disabled", true);
        DisableInputControll();
        ClearAllValidation();
        $("#subcategory-form").hide();
        $("#category-form").hide();
       
    });
</script>

<script src="~/Scripts/product-detail.js"></script>
}

turnk/src/ByDay.Web.UI/Views/Product/EditProduct.cshtml
@model ByDay.Web.UI.Models.ProductModel
@{
    ViewBag.Title = "EditProduct";
    var count = 0;
}
@{ string categoryName = ViewBag.CategoryName;}
@{ string categorySubName = ViewBag.CategorySubName;}
@*@{ string categoryId = ViewBag.CategoryId;}
    @{ string categorySubId = ViewBag.CategorySubId;}*@




@using (Html.BeginForm("EditProduct", "Product", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data", @id = "productEditForm" }))
{
    <div class="row">
        <div class="col-md-6">
            <div class="form-main-container">
                <div class="form-heading">
                    <span class="form-heading-icon"><i class="fa fa-bars"></i></span>
                    <h4>Product Category & Sub-category</h4>
                </div>
                <div class="form-container">
                    <div class="form-horizontal">
                        <div class="form-group category-form" id="categoryLabel-form">
                            <label class="col-md-4 control-label required-filed">Category Name</label>
                            <div class="col-md-8">
                                <input type="hidden" name="Id" value="@Model.Id" />
                                @Html.DropDownListFor(m => m.Id, new SelectList(Model.ProductCategoryList, "Id", "Name", Model.Id), "--Select--", new { @class = "form-control", id = "selectName" })
                                <a title="Add new category" id="category-form-btn">+</a>
                            </div>
                        </div>
                        <div class="form-group sub-form-gp" id="category-form">
                            <div class="col-md-12">
                                <div class="r1">
                                    @Html.TextBoxFor(m => m.CategoryName, new
                               {
                                   @class = "form-control",
                                   @id = "pro-validid",
                                   @placeholder = "New Category Name",
                                   maxlength = "100"
                               })
                                    <p id="proName-error" class="field-validation-error"></p>
                                </div>
                                <div class="r2">
                                    <input type="button" value="Save" onclick="return submitProductCategoryData();" class="theme-btn">
                                </div>
                            </div>
                        </div>
                        <div class="form-group category-form">
                            <label class="col-md-4 control-label required-filed">Sub-category Name</label>
                            <div class="col-md-8" id="subcatId">
                                @Html.DropDownListFor(m => m.SubCategoryId, new SelectList(Model.ProductSubCategoryList, "Id", "Name", Model.Id), "--Select--", new { @class = "form-control", id = "pro-subCatgory" })
                                <a title="Add new category" id="subcategory-form-btn">+</a>
                            </div>
                        </div>
                        <div class="form-group subcategory-form-gp" id="subcategory-form">
                            <div class="col-md-12">
                                <div class="r1">
                                    <input type="text" readonly name="categoryId" class="form-control" id="catId" placeholder="">
                                </div>
                                <div class="r2">
                                    @Html.TextBoxFor(m => m.Name, new
                               {
                                   @class = "form-control",
                                   @id = "proSub-validid",
                                   @placeholder = "New Sub Category",
                                   maxlength = "100"
                               })
                                    <p id="proSubName-error" class="field-validation-error"></p>
                                </div>
                                <div class="r3">
                                    <input type="button" value="Save" onclick="return submitProductSubCategoryData()" class="theme-btn">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-main-container">
                <div class="form-heading">
                    <span class="form-heading-icon"><i class="fa fa-bars"></i></span>
                    <h4>Product</h4>
                </div>
                <div class="form-container">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <label class="col-md-4 control-label required-filed">Product Name</label>
                            <div class="col-md-8">
                                @Html.TextBoxFor(x => x.ProductName, new
                           {
                               @class = "form-control",
                               @id = "proname-validid",
                               @placeholder = "Product Name",
                               maxlength = "100"
                           })
                                <p id="productName-error" class="field-validation-error"></p>

                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label required-filed">Product Price</label>
                            <div class="col-md-8">
                                @Html.TextBoxFor(m => m.Price, new
                           {
                               @class = "form-control",
                               @id = "price-validid",
                               @placeholder = "Price",
                               oncopy = "return false",
                               onpaste = "return false",
                               oncut = "return false",


                               maxlength = "25"
                           })


                                <p id="price-error" class="field-validation-error"></p>

                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label required-filed">Product Type</label>
                            <div class="col-md-8">
                                @Html.DropDownListFor(m => m.Type, new SelectList(new[]{
                                 new { Value = "", Text = "--Select--" },
                                 new { Value = "G", Text = "Gift" },
                                 new { Value = "C", Text = "Card" }
                             }, "Value", "Text"), new { @class = "form-control", @id = "producttype-validid" })

                                <p id="producttype-error" class="field-validation-error"></p>

                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label">Needs custom photo</label>
                            <div class="col-md-8">
                                @Html.DropDownListFor(m => m.IsCustomizable, new SelectList(new[]{
                                   new { Value = "false", Text = "No" },
                                 new { Value = "true", Text = "Yes" }
                             }, "Value", "Text"), new { @class = "form-control", @id = "iscustom-validid" })
                                <p id="iscustom-error" class="field-validation-error"></p>

                            </div>
                        </div>
                        <div class="form-group upload-product-image">
                            <label class="col-md-4 control-label required-filed">Upload Image</label>
                            <div class="col-md-8 upload-product-image">
                                <div class="col-md-4">

                                    <input type="hidden" name="URL" value="@Model.URL" />
                                    <img class="upload-image" src="@Model.URL">
                                </div>

                                <div class="col-md-8">
                                    <label for="file-upload" class="custom-file-upload" id="custom-file-upload">
                                        <i class="fa fa-image"></i> Image Upload
                                    </label>
                                    <input type="file" id="file-upload" class="form-control uploadimg" name="FileName" onchange="SelectProductImage(this);">

                                    <p id="uploadimage-error" class="field-validation-error"></p>

                                </div>

                            </div>
                        </div>
                        <div id="extraImages_" class="multi-image-wrap">

                            @foreach (var image in Model.ProductImages)
                            {
                                <div class="form-group upload-image-container upload-image-gp">
                                    @Html.HiddenFor(t => t.ProductImages[count].Id)
                                    @Html.HiddenFor(t => t.ProductImages[count].ProductId)
                                    @Html.HiddenFor(t => t.ProductImages[count].URL)

                                    <button class="gp-remove-image-btn enableUpload" onclick="deleteImage(this)">Delete</button>
                                    <div class="col-md-2 col-xs-2">
                                        <img class="upload-image" src="@image.URL" />
                                    </div>
                                    <div class="col-md-4 col-xs-4">
                                        <label for="file-upload--@count" class="custom-file-upload" id="custom-file-upload-@count">
                                            <i class="fa fa-image"></i> Image Upload
                                        </label>
                                        <input type="file" id="file-upload--@count" class="form-control enableUpload" onchange="SelectImage(this);">
                                    </div>
                                    <div class="col-md-6 col-xs-6">
                                        <div class="multiple-select">
                                            <ul></ul>
                                        </div>
                                    </div>
                                </div>
                                count = count + 1;
                            }
                        </div>
                        <div class="form-group" id="more-option">
                            <label class="col-md-4 control-label">&nbsp;</label>
                            <div class="col-md-8">
                                <div class="form-actions">
                                    <button type="button" id="btnAddMore" onclick="AddMoreRowsImage()" class="btn btn-default"> + Add More Image</button>
                                </div>
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-md-3 col-md-offset-2">
                                <input type="button" value="Edit Product" id="editPrductBtn" class="theme-btn">
                            </div>
                            <div class="col-md-3">
                                <input type="button" value="Update" id="savePrductBtnEdit" class="btn-default" disabled="disabled">
                            </div>
                            <div class="col-md-3">
                                <a href="@Url.Content("~/Product/Index")" id="CancelTip" class="theme-btn">Cancel</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
}
@section scripts{

    <script>
        $('#selectName').attr("disabled", true);
        $('#editPrductBtn').click(function () {

            $('#selectName').attr({ 'disabled': false });
            $("#savePrductBtnEdit").attr("disabled", false);
            $('#editPrductBtn').attr("disabled", true);
            //  EnableInputControll();
            EnableInputControll();
            $('#pro-subCatgory').attr("disabled", false);
        });


    </script>

    <script src="~/Scripts/product-detail.js"></script>
    <script>
        var eidtCategoryName = '@ViewBag.CategoryName';
        var editCategorySubName = '@ViewBag.CategorySubName';
        var categoryId = '@ViewBag.CategoryId';
        var categorySubId = '@ViewBag.CategorySubId';
        $(window).load(function () {
            var categoryName = '@(categoryName)';
            $('#selectName').attr({ 'disabled': false });
            $('#selectName').append($('<option selected></option>').val(categoryId).html(eidtCategoryName));
            $('#pro-subCatgory').append($('<option selected></option>').val(categorySubId).html(editCategorySubName));

            // $("#pro-subCatgory").append($("<option></option>").val(value.Id).html(value.Name));
        });
    </script>
}